lib/call.js, test/unit/call.js
* In previous commit I added setters using a normal function, however we want to use proper js getter/setters for obvious reasons.
* Helps with babblevoice/babble-sip#35
=> Properly fix setters

lib/call.js
* Fix possible race condition too.
=> Rework cleanup mechanism for channels disposal

lib/call.js
Play ringing if a call is established instead of sending 180
Play engaged tone if a call is hung up while established
=> Add audio to ringing and hangup

lib/call.js, package-lock.json, package.json
Tidy ups
1. Lint spaces and remove some dead code
2. simplify logical if statements - readability
3. fix the complexity of the hangup function
4. check play for a soup (just it is truthy)
5. remove the "from" field in caller id; it returns the " in the string for name - which then breaks other functions
6. complete jsdoc to function header
=> Bug hangup ringing compat remove from

lib/call.js
Fix recursion error on a getter
https://github.com/babblevoice/babble-sip/issues/375
=> Avoid infinite recursion

lib/call.js
This is for https://github.com/babblevoice/babble-sip/issues/10
=> Set privacy if privacy variable is present

lib/call.js
* For babblevoice/babble-sip#402
=> Add contact() method

lib/call.js, package-lock.json, package.json
User field should be uri encoded for dratchio
=> Bug uriencode user

lib/call.js
* See babblevoice/babble-sip#348.
=> Use name as callerid if number is not present

lib/call.js
Similar to netapi implementation.
=> 3 legged xfer sip

lib/call.js
* Fix babblevoice/babble-sip#480
=> Use user when name not present for remote party ids

lib/call.js, package-lock.json, package.json
When a reinvite occurs the local ip and port changes it continue to use the old sdp. Switch to reinvite which is more universal - plus in xfer specs.
=> Bug reinvite didnt publish change local ip

lib/call.js, package-lock.json, package.json
Add caller headers to reinvite - have to use different method as modify is only for sdp.
=> Bug caller id on reinvite

lib/call.js, package-lock.json, package.json
In order to maintain in CDR both destinations of all legs don't propagate this. This is different to called which it does make sense it is propogated.
=> Bug calledid propogation confusing

index.js, lib/call.js, package-lock.json, package.json
Ensure greater alignment with RFC 4028
=> Bug timer issues

lib/call.js, package-lock.json, package.json
=> Bug more caller id issues

lib/call.js, package-lock.json, package.json
VTech phones do not support timer - don't mandate by default (it was never intended to do this).
=> Bug check timer supported

lib/call.js, package-lock.json, package.json
An exception happened in test as a channel went away before the mix happened. Add a block for that.
=> Bug gap between answer and mix

lib/call.js, package-lock.json, package.json
We missed the 301 and 302 refer implementation. Added.
=> Bug handle 301 302

lib/call.js, package-lock.json, package.json
1. Corrected terms for party-calling
2. Corrected direction for those flags
3. Corrected priority and situations regarding caller id and called id
=> Bug party calling and related callerid improvements

lib/call.js, package-lock.json, package.json
Still problems with party direction call id.
=> Bug more caller id tweaks

lib/call.js, package-lock.json, package.json
This can cause exception if the related channel is closed
=> Bug unhandled exception

lib/call.js
https://github.com/babblevoice/babble-sip/issues/891
=> Set max timeout to 30min

README.md, lib/call.js, package-lock.json, package.json, test/interface/call.js, test/interface/early.js
we need more tests on what has happened
=> Feature add more counters

lib/call.js, package-lock.json, package.json
We did not check the caller id or name before creating the header - now reduced to allowed set of characters in both cases.
=> Bug sanatize caller
